### ISSUE TITLE
Fields of Mars V1 post-launch to-do list

### ISSUE THREAD

**Issue by larry0x** [mars-protocol/fields-of-mars#7]
## To-do list

- [ ] Split `martian-field` into two contracts, `credit-manager` and `autocompounder`
- [ ] Instead of using the `balance` callback, use [AstroZap contract](https://github.com/astroport-fi/astro-zap) to enter the DEX pool
- [ ] Instead of hardcoding `astro_token_info` and `astro_pair`, the contract should support arbitrary reward tokens; during harvesting, let the operator specifying swap routes and use Astroport Router to execute the swaps
- [ ] Simplify the string representation of adapters. E.g. Instead of `{"contract_addr":"terra..."}` it can be simply `terra...`. This could save gas when loading/saving the config
- [x] Merge health info (`bond_value`, `debt_value`, `ltv`) into the `position` and `positions` queries
- [x] Return global health info in the `state` query
- [x] Remove snapshots
- [x] Update `cw-asset` and `astroport-core` versions to latest

### Snapshot functionality will be deprecated

Will do this when informed by the frontend devs that they can calculate PnL without using the snapshots.

### The `health` query will be deprecated

Current we need to make two queries, `position` and `health`, to retrieve the full info regarding a user position:

```typescript
// v1.0
type PositionResponse = {
  bond_units: string,
  debt_units: string,
  unlocked_assets: Asset[],
};

// v1.0
type HealthResponse = {
  bond_amount: string,
  bond_value: string,
  debt_amount: string,
  debt_value: string,
  ltv: string | null,
};
```

In v1.1 these two will be merged into one:

```typescript
// v1.1
type PositionResponse = {
  bond_units: string,
  bond_amount: string,
  bond_value: string,
  debt_units: string,
  debt_amount: string,
  debt_value: string,
  ltv: string | null,
  unlocked_assets: Asset[],
};
```

### The `state` query will return `PositionResponse`

Since the strategy's global state has the same parameters as individual positions (bond and debt units/amount/value, LTV, unlocked assets...) we will simply return `PositionResponse` when querying the state.

## More features (for consideration in v1.2)

* Specify a common contract interface that strategies much implement in order to be included in the Mars protocol frontend
* Implement the "two-threshold system". During `update_position`, the LTV must either end up below a `user_threshold` or reduce compared to before the update. During `liquidate`, the LTV must be greater than a `liq_threshold`
* Instead of saving the whole `Config` in a giant `cw_storage_plus::Item` store, save the adapters under separate keys and only load the necessary ones (**gas savings**)
* For the `update_config` function, make it such that it only takes the parameters that needs to be changed, instead of the whole config
